### ISSUE TITLE
ActiveTCL URL broken?

### ISSUE THREAD

**Issue by jooleeanh** [protz/ocaml-installer#29]
Hello,

I'm a student in a Computer Science class, learning OCaml and the professor referenced to your installer for Windows users who wanted to program using the standard Eclipse Luna package (I am using the x32 version).
We were assigned a problem set using the tk library, and my Eclipse can't find it. After a lot of trial and error, uninstalling and reinstalling, I think that the reason is because I had not installed the ActiveTCL package when first installing it in September. But now that I try to install it using your latest installer (I am on Ocaml 4.01.0) and trying to just install ActiveTCL (everything else is already installed), I get this error:

"couldn't download the ActiveTCL installer: HTTP/1.1 404 Not Found"

Would you have an idea of what is the problem?

Thank you very much.

**Comment by bartvdo** [comment]
I have the same problem

**Comment by protz** [comment]
I guess it's not essential... I'm actually considering removing that 
Active TCL thing and instead list the extra step on the installer's webpage.

**Comment by msprotz** [comment]
ActiveTCL removed.
