### ISSUE TITLE
all gallium.inria.fr broken on protz.github.io/ocaml-installer/

### ISSUE THREAD

**Issue by ellisonch** [protz/ocaml-installer#36]
All of the links to http://galliulm.inria.fr, which are being used on http://protz.github.io/ocaml-installer/ , are broken.  I wanted to download the binaries, but couldn't.

**Comment by ellisonch** [comment]
I figured out the problem.  Apparently the server does not accept incoming connections from the VPN I was using, which is totally unfortunate.  Probably you can't do anything about this?

**Comment by msprotz** [comment]
I think it's just that the inria server went down as the offices were relocated from Rocquencourt to Paris.

**Comment by ellisonch** [comment]
Cool.  Bad timing :)  Thanks!
